### ISSUE TITLE
Jekyll Build On A Schedule

### ISSUE THREAD

**Issue by khalidabuhakmeh** [SyntaxC4-MSFT/JekyllExtension#2]
Hello,

I am currently running Jekyll in Azure App Services and it works like a charm. Thanks for your work.

I was wondering if the Azure Extension could also include a component that had a **webjob** that runs continually and builds the Jekyll site?

The reason I ask is because right now the extension only builds on deployments. This introduces and issue with the **[future](https://jekyllrb.com/docs/configuration/)** feature of Jekyll.

This WebJob component could be set via AppSettings to run on an interval of at least a day, but maybe even longer.

Thoughts?

**Comment by SyntaxC4** [comment]
it doesn't seem like it would be difficult to implement. I'll take a look at it the next time I have some availability to implement some new features.

As always, PRs are welcome :smile:

**Comment by SyntaxC4** [comment]
@khalidabuhakmeh - I have pushed an initial implementation of the webjob generation in **0.1.9**. Please feel free to check it out and provide feedback.
