### ISSUE TITLE
Similar to closed issue #1

### ISSUE THREAD

**Issue by kathweaver** [SyntaxC4-MSFT/JekyllExtension#4]
I am getting the same results as #1 

Went through the same steps but haven't run on my own machine. Also getting the same results.  It's at www.kweaver.us/github

**Comment by fboucher** [comment]
Did you set the Application setting, and reboot?

Here is a more detailed instruction search for the: **Option 2 - Jekyll Extension to Azure Web App**
http://www.frankysnotes.com/2016/03/6-ways-to-go-from-markdown-to-azure-web.html

**Comment by kathweaver** [comment]
Thanks!

I'm not sure which step I missed, probably the reboot. I was also looking at the source files.

I'm also didn't realize it would wipe out the whole site, but I'm not sure I care.
